### ISSUE TITLE
画面遷移図の作成

### ISSUE THREAD

**Issue by mimuro-lab** [mimuro-lab/TesseractForiPhone#1]
やる事

- [x] 画面遷移図の作成
- [x] アプリケーションの目的を記載する

**Comment by mimuro-lab** [comment]
# 画面遷移図
以下に作成した画面遷移図を置いておきます。
以後、変更変を加えるかもしれません。とりあえずで書いてみました。

![画面遷移図](https://user-images.githubusercontent.com/58100740/89983581-bfe58180-dcb2-11ea-8db4-8879a35aa37c.jpg)

**Comment by mimuro-lab** [comment]
@TakkuMattsu 

画面遷移図に関して、Xcodeでできる事についての質問があります。
今回作成した画面遷移図において、以下の事ができるのが前提となっております。
（画像やCSVファイルを一旦どこかに保存しておいて、パスを渡す事で、次のシーンで同じファイルにアクセスする）

* カメラで画像が取得できる事
* 画像をアプリ内に保存できる事
* 他のシーンから"画像パスの指定”などによって、画像にアクセスできる事（CSVファイルも同様）
* CSVファイルの表示ができる事

これらがXcode上で実現可能か、確認したいです。
（特に、画像ファイル等の保存方法、アクセス方法などは、あまり理解できておりません。
なので、できない様な事があるかもしれないです。）

**Comment by takkumattsu** [comment]
> @TakkuMattsu
> 
> 画面遷移図に関して、Xcodeでできる事についての質問があります。
> 今回作成した画面遷移図において、以下の事ができるのが前提となっております。
> （画像やCSVファイルを一旦どこかに保存しておいて、パスを渡す事で、次のシーンで同じファイルにアクセスする）
> 
> * カメラで画像が取得できる事
> * 画像をアプリ内に保存できる事
> * 他のシーンから"画像パスの指定”などによって、画像にアクセスできる事（CSVファイルも同様）
> * CSVファイルの表示ができる事
> 
> これらがXcode上で実現可能か、確認したいです。
> （特に、画像ファイル等の保存方法、アクセス方法などは、あまり理解できておりません。
> なので、できない様な事があるかもしれないです。）

@mimuro-lab 

いい感じだね！
わかってないことがしっかりリスト化されているのはGood！
iOSの開発のドキュメントは https://developer.apple.com/documentation にあります。
とはいえここからやりたいことを探すのはかなり最初は難しいと思うので以下の手順で調べて見てください。

1. ひとまずググってみる
2. ヒットした記事を見てやりたいことが出来るか確認
3. 利用しているメソッドやクラスをAppleの公式のリファレンスで調べて本当に使えそうか確認する

**Comment by mimuro-lab** [comment]
# このアプリケーションの最終目標
　このアプリケーションの最終目標は、スマートフォン等のデバイスを通じて、気軽にノート画像の解析を行う事である。
デバイスのカメラからノートの画像を取り込み、その画像の文章的・構造的特徴を抽出し、ユーザーが分かりやすい形で情報をまとめるアプリケーションを作る。今回はデバイスとしてはiPhoneを前提とし、ノート解析に使うツールはオープンソースOCRソフトであるTesseractを使用する。

# 今回の目的
　今回は、最終目標を達成する為の第一歩として、iPhoneから画像を取り込み、Tesseractから出力ファイルを作成する事を目的とする。Tesseractの使用に関しては、SwiftyTesseractを用いる。

・[SwiftyTesseract](https://github.com/SwiftyTesseract/SwiftyTesseract)
